# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'starup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for starup
  pod 'Parse'
  pod 'Parse/UI'
  pod 'AFNetworking'
  pod 'DateTools'
  pod 'MBProgressHUD'
  pod 'LinkedinIOSHelper', '~> 1.0.9'
  pod 'PayPalCheckout'
  pod 'ChatSDK'
  pod 'ChatSDKFirebase/Adapter'
  pod 'ChatSDKFirebase/Upload'
  pod 'ChatSDKFirebase/Push'
  
  plugin 'cocoapods-patch'

  target 'starupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'starupUITests' do
    # Pods for testing
  end

end
