# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'starup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for starup
  pod 'Parse'
  pod 'Parse/UI'
  pod 'AFNetworking'
  pod 'DateTools'
  pod 'MBProgressHUD'
  pod 'AppAuth'

  target 'starupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'starupUITests' do
    # Pods for testing
  end

end
